VERSION 0.7
FROM python:3.11
WORKDIR /backend

deps:
    RUN pip install poetry
    COPY pyproject.toml ./
    COPY poetry.lock ./

build:
    FROM +deps
    COPY . backend
    COPY dist dist
    SAVE ARTIFACT backend /backend
    SAVE ARTIFACT dist /dist

docker:
    COPY +build/backend
    ARG tag="latest"
    ENTRYPOINT ["python3", "/.backend"]
    SAVE IMAGE ongkagu-backend:$tag

check-format:
    FROM +deps
    COPY . backend
    RUN poetry install
    RUN poetry run ruff ./backend/
