VERSION 0.7
FROM oven/bun


deps:
    COPY package.json ./
    COPY bun.lockb ./
    RUN bun install

dev:
    FROM +deps
    COPY . .
    RUN bun run dev

check-format:
    FROM +deps
    COPY . .
    RUN bun run lint
    RUN bun run check

build:
    FROM +deps
    COPY . .
    RUN bun run build
    SAVE ARTIFACT build

docker:
    COPY +build .
    ARG tag='latest'
    ENTRYPOINT ["node", "build"]
    SAVE IMAGE ongaku-ui:$tag
